### ISSUE TITLE
Hope the author can open source CVPR2024 code for following research

### ISSUE THREAD

**Issue by mapstory6788** [liguopeng0923/liguopeng0923#1]
Hope the author can open source CVPR2024 code for following research

**Comment by liguopeng0923** [comment]
We have released the code 3 month ago.
https://github.com/liguopeng0923/UCVGL

**Comment by mapstory6788** [comment]
Wrong comments

**Comment by mapstory6788** [comment]
> We have released the code 3 month ago. https://github.com/liguopeng0923/UCVGL

Thank you.

**Comment by EugeneLiu01** [comment]
Thank you.

**Comment by yzhHoward** [comment]
Who is Guopeng Li?

**Comment by xjtulyc** [comment]
thank u
